export type Theme = 'light' | 'dark' | 'desert';

export type Route = 
  | 'home' 
  | 'fog-coins' 
  | 'auth' 
  | 'dashboard' 
  | 'profile'
  | 'earnings-dashboard'
  | 'events'
  | 'watch-ads'
  | 'pricing'
  | 'about'
  | 'careers'
  | 'press'
  | 'blog'
  | 'features'
  | 'api'
  | 'help-center'
  | 'community'
  | 'privacy-policy'
  | 'terms'
  | 'chat'
  | 'customer-service'
  | 'admin'
  | 'admin/ad-analytics';